# Sürümü en stabil olan 1.8'e çektik
loom_version=1.8-SNAPSHOT

# 1.21.4 Sürümleri
minecraft_version=1.21.4
loader_version=0.16.10
yarn_mappings=1.21.4+build.2
fabric_version=0.113.0+1.21.4

# Diğer Ayarlar
mod_version=1.0.0
maven_group=com.example
archives_base_name=fabric-lib
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
